### ISSUE TITLE
Using a non-standard font ruins the design.

### ISSUE THREAD

**Issue by 78kfb** [Beldex-Coin/bchat-android#13]
The program uses a non-standard font. It's nice and high quality, but it doesn't support other languages. If you write in Cyrillic, the system uses the standard Roboto font. You need to change to a standard font to support more languages. 

_And very missing is the choice of font size in chats, this is a basic cosmetic setting for any chat._

**Comment by snowman-45** [comment]
Thanks @78kfb  for pointing out. We are looking into multi-language support. Will fix this issue.

We will also include chat size customization in the same release.

**Comment by snowman-45** [comment]
Hi  @78kfb 
Please check this screenshot. Let us know what should be changed. we tried to write in Cyrrillic and added some text in English. We are not able to find any specific difference. Can you share your view on this, so that we can fix this. 

![cyrrilic text](https://user-images.githubusercontent.com/109149108/213109091-832c2573-4211-453d-b735-349c89b942e1.jpg)

**Comment by 78kfb** [comment]
I wrote the test messeges, font is different.
![Screenshot_2023-01-31-11-13-21-74_6308f1baa313afbaa088f49c47342d5a](https://user-images.githubusercontent.com/117159924/215732836-79963483-bf18-41cb-9bcd-a5cca72ec151.jpg)

**Comment by snowman-45** [comment]
Hi @78kfb , I can notice that text size a little bit bigger. We will update the font in upcoming release. Thanks for your valuable input.
